# This file contains text chunks extracted from the PDF.
# It is automatically generated by process_pdf.py

DOCUMENT_CHUNKS = [
    """Tomato Diseases & Disorders 
Factsheet | HGIC 2217 | Updated: May 26, 2021 |  Print |  Download (PDF) 
Tomatoes (Solanum lycopersicum) can be grown on almost any moderately well-drained 
soil type. A good supply of organic matter can increase yield and reduce production 
problems. Tomatoes and related vegetables, such as potatoes, peppers, and eggplants, 
should not be planted on the same land more than once in three years. Ideally, any cover 
crop or crop preceding tomatoes should be members of the grass family. Corn, an 
excellent rotation crop with tomatoes, supplies large amounts of organic matter and does 
not promote the growth of disease organisms that attack tomatoes. Certified seeds and 
plants are recommended and should be used whenever possible. 
Bacterial Wilt 
 
Bacterial wilt (Ralstonia solanacearum) causing a rapid wilting of tomato plants. 
Zachary Boone Snipes, ©2015 Clemson Extension""",
    """Bacterial Wilt 
 
Bacterial wilt (Ralstonia solanacearum) causing a rapid wilting of tomato plants. 
Zachary Boone Snipes, ©2015 Clemson Extension 
Bacterial wilt or Southern bacterial blight is a serious disease caused by Ralstonia 
solanacearum (formerly Pseudomonas solanacearum). This bacterium survives in the soil 
for extended periods and enters the roots through wounds made by transplanting, 
cultivation, insect feeding damage, and natural wounds where secondary roots emerge. 
Disease development is favored by high temperatures and high moisture. The bacteria 
multiply rapidly inside the water-conducting tissue of the plant, filling it with slime. This 
results in rapid wilt of the plant while the leaves stay green. If an infected stem is cut 
crosswise, it will look brown and tiny drops of yellowish ooze may be visible. 
Prevention & Treatment: Control of bacterial wilt of plants grown in infested soil is""",
    """Prevention & Treatment: Control of bacterial wilt of plants grown in infested soil is 
difficult. Rotation with non-susceptible plants, such as corn, beans, and cabbage, for at 
least three years provides some control. Do not use pepper, eggplant, potato, sunflower, or 
cosmos in this rotation. Remove and destroy all infected plant material. Plant only certified 
disease-free plants. The cultivar Kewalo is partially resistant to bacterial wilt but is an 
uncommon cultivar. Chemical control is not available for this disease. 
Consider growing all susceptible solanaceous plants (tomatoes, peppers, eggplants, and 
Irish potatoes) in a separate newly prepared garden site, completely separate from the 
original garden. Be sure to thoroughly hose off all soil from tiller tines and tools used in the 
original infested site before use in the new garden site.""",
    """Recently, several bacterial wilt resistant rootstocks for grafted tomatoes, peppers, and 
eggplants have been tested and found to have a high level of resistance. Grafted plants 
may be available. 
Early Blight 
 
Early blight (Alternaria linariae) on tomato foliage. 
Joey Williamson, ©2012 HGIC, Clemson Extension 
This disease is caused by the fungi Alternaria linariae (formally known as A. solani) and is 
first observed on the plants as small, brown lesions mostly on the older foliage. Spots 
enlarge and concentric rings in a bull’s-eye pattern may be seen in the center of the 
diseased area. The tissue surrounding the spots may turn yellow. If high temperature and 
humidity occur at this time, much of the foliage is killed. Lesions on the stems are similar 
to those on leaves and sometimes girdle the plant if they occur near the soil line (collar rot). 
On the fruits, lesions attain considerable size, usually involving nearly the entire fruit.""",
    """On the fruits, lesions attain considerable size, usually involving nearly the entire fruit. 
Concentric rings are also present on the fruit. Infected fruit frequently drops. 
The fungus survives on infected debris in the soil, on seed, on volunteer tomato plants, and 
other solanaceous hosts, such as Irish potato, eggplant, and black nightshade (a common, 
related weed). 
Prevention & Treatment: Use resistant or tolerant tomato cultivars. Use pathogen-free 
seed and do not set diseased plants in the field. Use crop rotation, eradicate weeds and 
volunteer tomato plants, space plants to not touch, mulch plants, fertilize properly, don’t 
wet tomato foliage with irrigation water, and keep the plants growing vigorously. Trim off 
and dispose of infected lower branches and leaves. 
To reduce disease severity, test the garden soil annually and maintain a sufficient level of 
potassium. Lime the soil according to soil test results. Side dress tomato plants monthly""",
    """potassium. Lime the soil according to soil test results. Side dress tomato plants monthly 
with calcium nitrate for adequate growth. 
If the disease is severe enough to warrant chemical control, select one of the following 
fungicides: mancozeb (very good); chlorothalonil or copper fungicides (good). Follow the 
directions on the label. See Table 1 for examples of fungicide products for home garden 
use. See Table 2 for tomato cultivars with resistance or tolerance to early blight. 
Late Blight 
Late blight is a potentially serious disease of potato and tomato and is caused by the water 
mold pathogen Phytophthora infestans. Late blight is especially damaging during cool, wet""",
    """weather. This pathogen can affect all plant parts. Young leaf lesions are small and appear 
as dark, water-soaked spots. These leaf spots will quickly enlarge, and a white mold will 
appear at the margins of the affected area on the lower surface of leaves. Complete 
defoliation (browning and shriveling of leaves and stems) can occur within 14 days from the 
first symptoms. Infected tomato fruits develop shiny, dark, or olive-colored lesions, which 
may cover large areas. Fungal spores are spread between plants and gardens by rain and 
wind. A combination of daytime temperatures in the upper 70s °F with high humidity is 
ideal for infection. 
Prevention & Treatment: The following guidelines should be followed to minimize late 
blight problems: 
• Keep foliage dry. Locate your garden where it will receive morning sun. 
• Allow extra room between the plants, and avoid overhead watering, especially late 
in the day. 
• Purchase certified disease-free seeds and plants.""",
    """in the day. 
• Purchase certified disease-free seeds and plants. 
• Destroy volunteer tomato and potato plants, as well as nightshade family weeds, 
such as Carolina horsenettle or black nightshade, which may harbor the fungus. 
• Do not compost rotten, store-bought potatoes. 
• Pull out and destroy diseased plants. 
• If the disease is severe enough to warrant chemical control, select one of the 
following fungicides: chlorothalonil (very good), copper fungicide, or mancozeb 
(good). See Table 1 for examples of fungicide products for home garden use. Follow 
the directions on the label. 
• Plant resistant cultivars. See Table 3 for tomato cultivars with resistance to late 
blight. 
 
Septoria leaf spot (Septoria lycopersici) on tomato. 
Joey Williamson, ©2013 HGIC, Clemson Extension 
Septoria Leaf Spot 
This destructive disease of tomato foliage, petioles, and stems (fruit is not infected) is 
caused by the fungus Septoria lycopersici. Infection usually occurs on the lower leaves""",
    """caused by the fungus Septoria lycopersici. Infection usually occurs on the lower leaves 
near the ground, after plants begin to set fruit. Numerous small, circular spots with dark 
borders surrounding a beige-colored center appear on the older leaves. Tiny black specks,""",
    """which are spore-producing bodies, can be seen in the center of the spots. Severely spotted 
leaves turn yellow, die, and fall off the plant. The fungus is most active when temperatures 
range from 68 to 77° F , the humidity is high, and rainfall or overhead irrigation wets the 
plants. Defoliation weakens the plant, reduces the size and quality of the fruit, and exposes 
the fruit to sunscald (see below). The fungus is not soil-borne but can overwinter on crop 
residue from previous crops, decaying vegetation, and on some weeds related to tomato. 
Prevention & Treatment: Most currently grown tomato cultivars are susceptible to 
Septoria leaf spot. Crop rotation of 3 years and sanitation (removal of crop debris) will 
reduce the amount of inoculum. Do not use overhead irrigation. Repeated fungicide 
applications with chlorothalonil (very good) or copper fungicide, or mancozeb (good) will 
keep the disease in check. See Table 1 for examples of fungicide products for home garden 
use.""",
    """keep the disease in check. See Table 1 for examples of fungicide products for home garden 
use. 
Leaf Mold 
The fungus Passalora fulva causes leaf mold. It is first observed on older leaves near the 
soil where air movement is poor and humidity is high. The initial symptoms are pale green 
or yellowish spots on the upper leaf surface, which enlarge and turn a distinctive yellow. 
Under humid conditions, the spots on the lower leaf surfaces become covered with a gray, 
velvety growth of the spores produced by the fungus. When infection is severe, the spots 
coalesce, and the foliage is killed. Occasionally, the fungus attacks stems, blossoms and 
fruits. Green and mature fruit can have a black, leathery rot on the stem end. 
 
Leaf mold (Passalora fulva) on tomato foliage. 
Joey Williamson, ©2012 HGIC, Clemson Extension 
 
Leaf mold (Passalora fulva) on lower leaf surface. 
Joey Williamson, ©2012 HGIC, Clemson Extension""",
    """Joey Williamson, ©2012 HGIC, Clemson Extension 
 
Leaf mold (Passalora fulva) on lower leaf surface. 
Joey Williamson, ©2012 HGIC, Clemson Extension 
The fungus survives on crop residue and in the soil. Spores are spread by rain, wind, or 
tools. Seeds can be contaminated. The fungus is dependent on high relative humidity and 
high temperature for disease development. 
Prevention & Treatment: Crop residue should be removed from the field. Staking and 
pruning to increase air circulation helps to control the disease. Space tomato plants 
further apart for better air circulation between plants. Avoid wetting leaves when watering. 
Rotate with vegetables other than tomatoes. Using a preventative fungicide program with""",
    """chlorothalonil, mancozeb, or copper fungicide, can control the disease. See Table 1 for 
fungicide products for home garden use. 
Bacterial Spot 
This disease is caused by several species of the bacterium Xanthomonas (but primarily 
by Xanthomonas perforans), which infect green but not red tomatoes. Peppers are also 
infected. The disease is more prevalent during wet seasons. Damage to the plants includes 
leaf and fruit spots, which result in reduced yields, defoliation, and sunscalded fruit. The 
symptoms consist of numerous small, angular to irregular, water-soaked spots on the 
leaves and slightly raised to scabby spots on the fruits. The leaf spots may have a yellow 
halo. The centers dry out and frequently tear. 
 
Bacterial Spot (Xanthomonas perforans) symptoms can be seen on both foliage and 
tomato fruit under ideal conditions. 
Zack Snipes, ©2020, Clemson Extension 
 
Bacterial Spot (Xanthomonas perforans) symptoms on tomato leaves.""",
    """tomato fruit under ideal conditions. 
Zack Snipes, ©2020, Clemson Extension 
 
Bacterial Spot (Xanthomonas perforans) symptoms on tomato leaves. 
Zachary Boone Snipes, ©2015 Clemson Extension 
The bacteria survive the winter on volunteer tomato plants and on infected plant debris. 
Moist weather is conducive to disease development. Most outbreaks of the disease can be 
traced back to heavy rainstorms that occurred in the area. Infection of leaves occurs 
through natural openings. Infection of fruits must occur through insect punctures or other 
mechanical injuries. 
Bacterial spot is difficult to control once it appears in the field. Any water movement from 
one leaf or plant to another, such as splashing raindrops, overhead irrigation, and touching 
or handling wet plants, may spread the bacteria from diseased to healthy plants. 
Prevention & Treatment: Only use certified disease-free seeds and plants. Avoid areas""",
    """Prevention & Treatment: Only use certified disease-free seeds and plants. Avoid areas 
that were planted with peppers or tomatoes during the previous year. Avoid overhead 
watering by using drip or furrow irrigation. Remove and dispose of all diseased plant 
material. Prune plants to promote air circulation. Spraying with a copper fungicide will give 
fairly good control of the bacterial disease. Follow the instructions on the label. See Table 1 
for fungicide products for home garden use. 
Tomato Pith Necrosis""",
    """Tomato pith necrosis is usually an early season disease that occurs in greenhouse and high 
tunnel tomato production. However, during cool and rainy spring weather, tomato pith 
necrosis may infect tomatoes and occasionally peppers in home vegetable gardens. Pith 
necrosis is caused by multiple species of soil-borne Pseudomonas bacteria, 
including Pseudomonas corrugata, as well as Pectobacterium carotovorum 
(a cause of bacterial soft rot). These bacteria are considered weak pathogens that infect 
rapidly growing tomato plants during cloudy, cool, and moist environmental conditions. 
Symptoms: The early symptoms of this disease are blackened (necrotic) areas on the 
stems, which may first appear adjacent to leaf petioles. The blackened areas coalesce and 
extend as a band along the stem, as well as out onto the leaf petioles. Portions of leaf 
blades also may become blackened following infection of the leaf petiole.""",
    """blades also may become blackened following infection of the leaf petiole. 
As the disease progresses, the bacteria colonize the interior of the stems, which may cause 
the stem to split. Stems may shrink, crack, and the pith (the stem interior) may become 
segmented or laddered. Eventually, the stems become hollow inside. This stem damage 
cuts the water supply off to the upper portions of the tomato plant so that upper leaves 
may yellow and the shoots wilt. 
 
With tomato pith necrosis, brown (necrotic) areas on stems often begin where leaves 
attach and spread down the adjacent leaf petiole. 
Joey Williamson, ©2018 HGIC, Clemson Extension 
 
The necrotic stem lesions develop into bands that extend several inches up and down the 
stem from the point of infection. After extending onto leaf petioles, necrotic areas appear 
on the leaf blades. Eventually, entire leaves will wither. 
Joey Williamson, © 2018 HGIC, Clemson Extension""",
    """on the leaf blades. Eventually, entire leaves will wither. 
Joey Williamson, © 2018 HGIC, Clemson Extension 
 
As the bacterial infection progresses, more of the main stem turns brown and dies. 
This cuts the water supply off to the plant parts above, which wilt. 
Joey Williamson, © 2018 HGIC, Clemson Extension 
 
There may be the appearance of adventitious roots that erupt from the main stems of 
tomato plants infected with tomato pith necrosis. 
Joey Williamson, © 2018 HGIC, Clemson Extension""",
    """Another symptom is the production of large numbers of adventitious roots that burst forth 
from larger stems. However, this type of root formation on stems also occurs with tomato 
bacterial canker and from damage by spray drift exposure by dicamba, which is a very 
common broadleaf weed killer for use on lawns. 
Symptoms on green developing fruit may or may not be present, which is a greasy, water-
soaked area on the blossom end of the fruit. This fruit symptom is very similar to that of two 
other diseases called late blight and buckeye rot of tomato. 
Identify which disease is affecting the tomato crop by submitting a plant sample through 
the local Extension office. The plant material will be sent for a fee to the Clemson Plant & 
Pest Diagnostic Clinic for diagnosis and control recommendations. 
Control: As the weather becomes warmer, plants may recover as the rapid spring growth 
slows. Do not use over-head irrigation to water the garden, but water at the base of the""",
    """slows. Do not use over-head irrigation to water the garden, but water at the base of the 
plants by drip irrigation, soaker hoses, or by hand with a garden hose. The frequency of 
irrigation should be increased to provide adequate soil moisture for recovery. However, if 
plants succumb to pith necrosis, carefully remove and dispose of diseased plants, 
including roots. 
This disease severity is enhanced by excessive nitrogen fertilization during early season 
growth. Follow fertilization recommendations by soil test results. For more information, 
see HGIC 1652, Soil Testing, and HGIC 1323, Tomato. 
Because these soil-inhabiting bacteria can exist in the soil until the next season, practice a 
3-year crop rotation within the vegetable garden. In the future, space out tomato plants in 
the garden to 3 feet apart. This will improve air circulation around plants and enhance the 
drying of foliage from dew or rainfall. Plant according to the recommended spring planting""",
    """drying of foliage from dew or rainfall. Plant according to the recommended spring planting 
dates in HGIC 1256, Planning a Garden. Avoid planting in early spring when conditions are 
cool and moist. There are no spray treatments to reduce disease. 
Buckeye Rot 
Buckeye rot is a disease of the fruit caused by the 
fungus Phytophthora nicotianae var. parasitica. The first fruit symptoms appear as 
brownish spots, often at the point of contact between the fruit and the soil. As the spots 
enlarge, dark, concentric rings can be seen. Lesions of buckeye rot resemble those of late 
blight, except that the former remain firm and smooth, whereas late blight lesions become 
rough and are slightly sunken at the margins. Under moist conditions, a white, cottony 
fungal growth appears on the buckeye rot lesions. With time, the entire fruit will rot. The 
fungus does not affect the foliage. The disease is most common during periods of""",
    """prolonged warm, wet weather and in poorly drained soils. The fungus survives in the soil 
and is spread by surface water and rain. Peppers are also susceptible to this disease. 
Prevention & Treatment: Avoid compacted, poorly drained soils (grow plants in raised 
beds). Rotation, sanitation, staking, and mulching will help reduce the disease. Fungicide 
sprays with chlorothalonil, mancozeb, or copper fungicides will give fairly good control of 
buckeye rot. See Table 1 for examples of fungicide products for home garden use. 
Anthracnose 
 
Anthracnose (Colletotrichum species) on tomato fruit. 
Joey Williamson, ©2013 HGIC, Clemson Extension 
Anthracnose on tomatoes is caused by a group of fungi within the genus Colletotrichum, 
and these species are primarily pathogens of the tomato fruit. As the fruit are ripening, the 
symptoms first become noticeable as small, circular indented areas, which later develop""",
    """symptoms first become noticeable as small, circular indented areas, which later develop 
darkened centers. The diseased spots continue to grow larger with time as each infection 
site also spreads deeper into the fruit. With warm, moist, and humid weather (from rainfall 
or overhead irrigation), the fungus produces salmon-colored spores that are exuded from 
the black fungal material in the center of the spots. These spores are spread by splashing 
water. 
Prevention & Treatment: Purchase disease-free seed, as the fungus that causes 
anthracnose of tomato may be within the seed. Tomato seed may be treated by soaking 
them in hot water (122 ºF) for 25 minutes to destroy the fungus. Some varieties of tomatoes 
have resistance to anthracnose, such as Chef’s Choice Orange Hybrid. 
Do not overhead irrigate tomatoes, as splashing water aids in the spread of fungal spores. 
Plant the garden in a sunny site and stake or cage tomato plants to provide better air""",
    """Plant the garden in a sunny site and stake or cage tomato plants to provide better air 
movement and leaf drying conditions. Keep the garden weed-free, as the presence of 
weeds may raise humidity levels around plants and slow drying conditions. 
Because this disease affects other plants in the tomato family (Solanaceae), such as 
eggplants and peppers, the site for the tomatoes should not be planted again with 
solanaceous plants for at least a year. Some weeds that infest the garden are also in the 
same family, which is another reason to keep the garden free of weeds. Fungal spores can 
remain in the soil to infect plants the following year. Mulching the garden helps create a 
barrier between the soil surface and the fruit to reduce infections. 
Some insects feed on ripe fruit, such as leaf-footed plant bugs and stink bugs. Their feeding 
punctures the skin of the fruit and allows the fungus to infect.""",
    """Harvest tomato fruit daily as soon as they are ripe. Remove and destroy crop debris as soon 
as the crop has finished bearing. Do not add debris to compost. 
Fungicide sprays can help reduce disease. Products containing mancozeb or 
chlorothalonil can be sprayed weekly to reduce infection. Follow label directions. There is a 
five-day waiting period between spraying and picking if using mancozeb, and a one-day 
waiting period for using chlorothalonil. See Table 1 for examples of products containing this 
active ingredient. 
Fusarium Wilt 
This is a warm-weather disease caused by the fungus Fusarium oxysporum. The first 
indication of disease in small plants is a drooping and wilting of lower leaves with a loss of 
green color followed by wilting and death of the plant. Often leaves on only one side of the 
stem turn golden yellow at first. The stem of wilted plants shows no soft decay, but when 
cut lengthwise, the lower stem will have a dark brown discoloration of the water-""",
    """cut lengthwise, the lower stem will have a dark brown discoloration of the water-
conducting vessels. The fungus is soil-borne and passes upward from the roots into the 
water-conducting system of the stem. Blocking of the water-conducting vessels is the main 
reason for wilting. Invasion occurs through wounds in roots growing through infested soil. 
Long-distance spread is through seed and transplants. 
Prevention & Treatment: For control, grow plants in pathogen-free soil, use disease-free 
transplants, and grow only cultivars with at least resistance to races 1 and 2 of Fusarium 
wilt (indicated by FF following the tomato cultivar name). Some newer cultivars are 
resistant to races 1, 2, and 3, and are found listed in Table 4. Raising the soil pH to 6.5 – 7.0 
and using nitrate nitrogen (such as in calcium nitrate) rather than ammoniacal nitrogen (as 
in 5-10-10, 10-10-10, or 34-0-0) will retard disease development. No chemical control is 
available.""",
    """in 5-10-10, 10-10-10, or 34-0-0) will retard disease development. No chemical control is 
available. 
 
Sclerotia and mycelium of Athelia rolfsii (synonym Sclerotium rolfsii) 
Zachary Boone Snipes, ©2015 Clemson Extension 
Southern Blight 
The fungus Athelia rolfsii (previously called Sclerotium rolfsii) causes this disease. The first 
symptom is the drooping of leaves suggestive of other wilts. On the stems, a brown, dry rot 
develops near the soil line. White fungal growth with brown mustard seed-sized sclerotia 
may be visible. The stem lesion develops rapidly, girdling the stem and resulting in sudden 
and permanent wilt of all aboveground parts. Frequently, a white fungal mat covers the 
lesions. The fungus can also attack fruits where they touch the soil.""",
    """The fungus can survive for years in soil and plant debris. It is favored by moist conditions 
and high temperatures. 
Prevention & Treatment: Crop rotation with non-susceptible grass crops and removal of 
plant debris immediately after harvest will help to control the disease. Do not plant 
tomatoes after beans, pepper, or eggplant. Calcium nitrate may be applied at 
transplanting. 
Seedling Disease (Damping-off) 
The fungi Pythium and Rhizoctonia cause damping-off of tomato seedlings. Seedlings fail 
to emerge from the soil in the greenhouse, or small seedlings wilt and die soon after 
emergence or transplanting. Surviving plants have water-soaked areas on the stem close to 
the soil line. 
Prevention & Treatment: Damping-off is often a problem in plants that are planted too 
early in the spring. The fungi are more active in cool, wet, rich soils. To prevent damping-off, 
take these precautions: 
• Start seeds indoors in sterilized potting mix and use new or clean containers.""",
    """take these precautions: 
• Start seeds indoors in sterilized potting mix and use new or clean containers. 
• Do not start seeds in soil that has a high nitrogen level. Add nitrogen fertilizer after 
the seedlings have produced their first true leaves. 
• Allow the surface of the soil to dry between waterings. 
Tomato Spotted Wilt 
Tomato spotted wilt virus (TSWV) is spread by tiny insects called thrips, which acquire the 
virus by feeding on one of many infected weeds or ornamental hosts, and then spread it to 
the developing tomato plants. Several weeks after transplanting the tomato plants into the 
garden, random plants may appear stunted, and younger leaves may be marked with 
bronze or dark spots or have prominent purple veins. Often the upper foliage will become 
twisted and cupped as the bronze areas expand. Fruits may have yellow spots. Younger 
plants may wilt and die, but older plants may survive and bear discolored fruit that may not 
fully ripen.""",
    """plants may wilt and die, but older plants may survive and bear discolored fruit that may not 
fully ripen. 
Prevention & Treatment: Eliminating weeds in the garden is the first step in reducing the 
chance of acquiring TSWV . Keeping the grass and weeds mowed in areas surrounding the 
garden may reduce the spread of thrips onto susceptible garden plants. Weeds in the 
garden area during the winter may harbor both the thrips and the virus. For best prevention, 
remove the old crop debris, till, and then mulch the garden for the winter to keep weeds 
and thrips down for the next year.""",
    """TSWV symptoms on tomato foliage. 
Meg Williamson, ©2012 Plant Problem Clinic, Clemson University 
 
TTSWV symptoms on tomato fruit. 
Meg Williamson, ©2012 Plant Problem Clinic, Clemson University. 
 
TSWV infected vines will bear discolored fruit that may not fully ripen. 
T.J. Savereno, ©2018 Clemson Extension 
Reflective (aluminum or silver-colored) mulch beneath the tomato plants may reduce the 
number of thrips that arrive and feed upon the plants. If reflective mulch is not available, 
paint black plastic mulch silver before transplanting the tomatoes. 
There is no cure for a plant with TSWV . Roguing or removing infected plants immediately 
from the garden may help reduce the incidence of disease on additional plants. However, 
feeding by thrips can transmit the virus to plants within minutes. Because of this rapid 
infection time, insecticidal sprays may be of no use for the home gardener. 
Seeds of several TSWV-resistant cultivars of tomatoes are available from mail-order seed""",
    """Seeds of several TSWV-resistant cultivars of tomatoes are available from mail-order seed 
companies. These cultivars are resistant but not totally immune. They may acquire the 
virus, but yields and fruit quality may remain acceptable. Look for cultivars with resistance 
if this has been a problem in the past. See Table 5 below for recommended TSWV-resistant 
cultivars. 
Tomato Yellow Leaf Curl 
 
Tomato plant with Tomato yellow leaf curl virus. 
Zachary Boone Snipes, ©2015 Clemson Extension 
Tomato yellow leaf curl virus (TYLCV) is not seed-borne but is transmitted by whiteflies. This 
disease is extremely damaging to fruit yield in both tomato and pepper crops. Whiteflies 
may bring the disease into the garden from infected weeds nearby, such as various 
nightshades and jimsonweed. After infection, tomato plants may be symptomless for as 
long as 2 to 3 weeks. 
Symptoms in tomato plants are the upward curling of leaves, yellow (chlorotic) leaf""",
    """long as 2 to 3 weeks. 
Symptoms in tomato plants are the upward curling of leaves, yellow (chlorotic) leaf 
margins, smaller leaves than normal, plant stunting, and flower drop. If tomato plants are""",
    """infected early in their growth, there may be no fruit formed. Infected plants may appear 
randomly throughout the garden. Pepper plants may also become infected, but will show 
no symptoms. 
Prevention & Treatment: Removal of plants with initial symptoms may slow the spread of 
the disease. Rogued (pulled out) infected plants should be immediately bagged to prevent 
the spread of the whiteflies feeding on those plants. Keep weeds controlled within and 
around the garden site, as these may be alternate hosts for whiteflies. Reflective mulches 
(aluminum or silver-colored) can be used in the rows to reduce whitefly feeding. 
Low concentration sprays of a horticultural oil or canola oil will act as a whitefly repellent, 
reduce feeding and possibly transmission of the virus. Use a 0.25 to 0.5% oil spray (2 to 4 
teaspoons horticultural or canola oil & a few drops of dish soap per gallon of water) weekly. 
Examples of products containing horticultural oil are:""",
    """Examples of products containing horticultural oil are: 
Bonide All Seasons Spray Oil Concentrate 
• Ferti-lome Horticultural Oil Spray Concentrate 
• Monterey Horticultural Oil Concentrate 
• Southern Ag Parafine Horticultural Oil 
• Summit Year Round Horticultural Oil Concentrate 
At the end of the season, remove all susceptible plants and burn or dispose of them. See 
Table 6 for tomato cultivars with resistance to Tomato yellow leaf curl virus. 
Other Viruses 
Different viruses cause different symptoms on tomatoes. Symptoms of virus infection may 
appear as light and dark green mottling of the leaves. Tobacco mosaic virus (TMV) causes a 
mottling of older leaves and may cause the malformation of leaflets, which may become 
shoestring-like in shape. 
Viruses are highly infectious and readily transmitted by any means that introduces even a 
minute amount of sap from infected into healthy plants. 
Prevention & Treatment: There are no chemical controls for viruses. Remove and destroy""",
    """minute amount of sap from infected into healthy plants. 
Prevention & Treatment: There are no chemical controls for viruses. Remove and destroy 
infected plants promptly. Wash hands thoroughly after smoking (the Tobacco mosaic 
virus may be present in certain types of tobacco) and before working in the garden. 
Eliminate weeds in and near the garden. Control insects (thrips and whiteflies) that carry 
viruses (see HGIC 2218, Tomato Insect Pests).""",
    """Rotate tomatoes with crucifers (such as cabbage, broccoli, and turnips). Use reflective 
mulches. Use virus-resistant tomato cultivars. Many cultivars have Tobacco mosaic 
virus (TMV) resistance (the letter T follows the cultivar name), such as Bush Celebrity, Bush 
Early Girl, Jetsetter, Big Beef, Celebrity, Sweet Cluster, Sweet Million (cherry), and Super 
Marzano (paste). 
 
Galled tomato roots caused by root-knot nematodes (Meloidogyne species). 
Zachary Boone Snipes, ©2015 Clemson Extension 
Root-knot Nematodes 
Root-knot nematodes (Meloidogyne species) are microscopic worms that live in the soil 
and in plant roots. Affected plants are usually stunted, discolored, and may die. Knots or 
galls develop on the roots. 
Prevention & Treatment: When nematodes are not yet present, move the tomato crop to a 
different area within the garden every year, purchase disease-free plants, pull up and 
dispose of roots immediately after harvest, and use resistant cultivars (indicated by N""",
    """dispose of roots immediately after harvest, and use resistant cultivars (indicated by N 
following tomato cultivar name). See Table 7 for cultivars resistant to root-knot nematodes. 
When root-knot nematodes are present, relocate the garden to a nematode-free area. Use 
nematode resistant tomato cultivars. Establish a rotation system using marigold cultivars 
Tangerine, Petite Gold, or Petite Harmony, which reduce root-knot nematode populations in 
soils. For more information, see HGIC 2216, Root-Knot Nematodes in the Vegetable 
Garden. 
Disorders 
 
Blossom end rot symptoms on tomato fruit. 
Joey Williamson, ©2009 HGIC, Clemson Extension 
Blossom End Rot: Blossom end rot is a physiological disorder of tomato. Symptoms are 
water-soaked spots on the blossom end of the fruit. These spots enlarge and become 
black. Secondary infection by decay-causing organisms usually follows. 
The cause of this disorder is a calcium deficiency in the developing fruit. Extreme""",
    """The cause of this disorder is a calcium deficiency in the developing fruit. Extreme 
fluctuations in moisture, rainy or cloudy weather with high humidity, cool temperatures, 
insufficient soil calcium, root pruning from nearby cultivation, and excessive ammoniacal 
(NH4 +) nitrogen, potassium, or magnesium fertilization can also increase the chances of 
blossom end rot, especially early in the season.""",
    """Prevention & Treatment: Late spring planting of tomatoes should be at the recommended 
date for your area. The soil should be limed according to recommendations of a soil 
analysis report to bring the soil pH to 6.5 and to provide adequate calcium levels in the soil. 
Limestone is best applied 3 to 6 months in advance and tilled into the garden soil. Follow 
the soil report for recommendations for pre-plant nutrient (fertilizer) applications. If 
calcium levels are not sufficient, but the soil pH is correct, then gypsum (calcium sulfate) 
is best tilled into the soil before planting at 1 to 2 pounds per 100 square feet. 
Avoid excessive potassium or magnesium fertilization as these nutrients will compete with 
calcium for uptake by the plants. Epsom salt is an example of a magnesium source, so do 
not apply to garden soil unless a recent soil report indicates a magnesium deficiency. 
Avoid ammoniacal nitrogen fertilizers for sidedress applications (beside or around the""",
    """Avoid ammoniacal nitrogen fertilizers for sidedress applications (beside or around the 
plants), as ammoniacal nitrogen also will compete with calcium for uptake. Examples of 
fertilizers with ammoniacal nitrogen are ammonium sulfate, ammonium nitrate, and most 
complete fertilizers, such as 10-10-10. A calcium nitrate (15.5-0-0) side dress fertilizer is 
usually the best choice and is applied monthly at 2 pounds per 100 feet of row. 
Maintain a uniform supply of moisture through irrigation and adequate soil mulches. 
Mulches will not only keep the soil cooler and more evenly moist but will suppress weeds, 
thus reducing the need for nearby cultivation that may damage tomato roots. Remove fruit 
with blossom end rot symptoms from the plants. 
However, if blossom end rot occurs because the soil was not tested and neither lime nor 
gypsum was applied pre-plant, then the application of gypsum at 1 to 2 pounds per 100""",
    """gypsum was applied pre-plant, then the application of gypsum at 1 to 2 pounds per 100 
square feet as a sidedress supplement has proven beneficial. See Table 8 for tomato 
cultivars with resistance to blossom end rot. 
Sunscald: Sunscald occurs when tomatoes are exposed to the direct rays of the sun during 
hot weather. It is most common on green fruit. Decay causing fungi frequently invade the 
damaged tissue. 
Prevention: Cover exposed fruits. Control leaf diseases, as foliage shades the fruit. 
Growth Cracks: Tomatoes crack when environmental conditions (drought followed by 
heavy rain or watering) encourage rapid growth during ripening. Some cracks may be deep, 
allowing decay organisms to enter the fruit and cause fruit rot. 
Prevention: Maintain even soil moisture with regular watering and adequate mulch. Some 
tomato cultivars are crack-tolerant; see Table 9 for suggested cultivars. 
Poor Fruit Set: Poor fruit set occurs for several reasons:""",
    """• Extreme temperatures: The blossoms drop off without setting fruit when 
temperatures are below 55 °F or above 90 °F for extended periods. Try Arkansas 
Traveler, Talladega Hybrid, Homestead 24, Bella Rosa Hybrid, Top Gun Hybrid, Solar 
Fire Hybrid, Florida 91 Hybrid, Sioux, or Costoluto Genovese for heat-tolerance. 
• Dry soil: Blossoms dry and fall when the plants do not receive enough water. 
• Shading: Few blossoms are produced when the plants receive less than six hours of 
sun a day. 
• Excessive nitrogen: High nitrogen levels in the soil promote leaf growth at the 
expense of blossom and fruit formation. Correct the nitrogen imbalance with 
superphosphate or 0-20-20 fertilizer. 
Catfacing: This is a disorder caused by cold temperatures during fruit set. The fruit is 
extremely malformed and scarred, usually at the blossom end. Fruits that develop later in 
the season will not be affected. The cultivar Homestead 24 is resistant to catfacing.""",
    """the season will not be affected. The cultivar Homestead 24 is resistant to catfacing. 
 
Tomato plant with Tomato yellow leaf curl virus. 
Zachary Boone Snipes, ©2015 Clemson Extension 
Leaf Roll: Leaf roll of tomatoes may be caused by high temperatures, prolonged periods of 
wet soil conditions, and drought. It may also occur when tomatoes are pruned severely or 
when nearby tilling damages roots. The symptom is mostly on older leaves, with an upward 
curling of the leaflets, but may progress to affect up to 75 percent of the foliage. The rolled 
leaves may feel leathery and stiff. Often the condition of leaf roll occurs once the plants are 
under the stress of a heavy fruit set. Some cultivars are more prone to leaf roll than others. 
Prevention & Treatment: The symptom of leaf roll does not significantly damage the crop. 
To help prevent this disorder, tomatoes should be planted on well-drained soil and be""",
    """To help prevent this disorder, tomatoes should be planted on well-drained soil and be 
irrigated during periods of drought. For more information on physiological leaf roll, please 
see HGIC 2222, Tomato Leaves Rolling? 
Herbicide Injury: Drift from nearby sprays of broadleaf weed killers used on turfgrass, such 
as 2,4-D and dicamba, and non-specific herbicides, such as glyphosate, may severely 
damage tomato plants. 
Initial symptoms of glyphosate injury on tomatoes are characteristically seen as 
white/yellow discoloration at the base of the leaflets.""",
    """Distortion of tomato stems and foliage due to exposure to spray drift of 2,4-D herbicide. 
Joey Williamson, ©2014 HGIC, Clemson Extension 
 
Initial symptoms of glyphosate injury on tomatoes are characteristically seen as 
white/yellow discoloration at the base of the leaflets. 
Joey Williamson, HGIC, Clemson Extension 
Caution: Pollinating insects, such as honey bees and bumblebees, can be adversely 
affected by the use of pesticides. Avoid the use of spray pesticides (both insecticides and 
fungicides), as well as soil-applied, systemic insecticides unless absolutely necessary. If 
spraying is required, always spray late in the evening to reduce the direct impact on 
pollinating insects. Always try less toxic alternative sprays first for the control of insect 
pests and diseases. For example, sprays with insecticidal soap, horticultural oil, neem oil 
extract, spinosad, Bacillus thuringiensis (B.t.), or botanical oils can help control many""",
    """extract, spinosad, Bacillus thuringiensis (B.t.), or botanical oils can help control many 
small insect pests and mites that affect garden and landscape plants. Neem oil extract or 
botanical oil sprays may also reduce plant damage by repelling many insect pests. Practice 
cultural techniques to prevent or reduce the incidence of plant diseases, including pre-
plant soil improvement, proper plant spacing, crop rotation, applying mulch, applying lime 
and fertilizer based on soil test results, and avoiding overhead irrigation and frequent 
watering of established plants. Additionally, there are less toxic spray fungicides that 
contain sulfur or copper soap, and biological control sprays for plant diseases that 
contain Bacillus subtilis. However, it is very important always to read and follow the label 
directions on each product. For more information, contact the Clemson Extension Home & 
Garden Information Center.""",
    """directions on each product. For more information, contact the Clemson Extension Home & 
Garden Information Center. 
Table 1. Fungicide Products for Home Garden Disease Control on Tomatoes. 
Fungicide Active Ingredient Examples of Products Containing the Active Ingredient 
Chlorothalonil 
Bonide Fungonil Concentrate; & RTU1 
Ferti-lome Broad Spectrum Landscape & Garden Fungicide Conc. ; & RTU1 
GardenTech Daconil Fungicide Concentrate 
Hi-Yield Vegetable, Flower, Fruit & Ornamental Fungicide Conc. 
Ortho MAX Garden Disease Control Concentrate 
Southern Ag Liquid Ornamental & Vegetable Fungicide Conc. 
Tiger Brand Daconil Concentrate""",
    """Mancozeb 
Bonide Mancozeb Flowable with Zinc Concentrate 
Southern Ag Dithane M-45 
Copper Fungicide2 
Bonide Copper Fungicide Spray or Dust (wettable powder; 3.98%) 
Bonide Liquid Copper Concentrate (a copper soap; 1.8%) 
Bonide Liquid Copper Fungicide RTU1 
Camelot Fungicide/ Bactericide Concentrate (a copper soap) (1.8%) 
Concern Copper Soap Fungicide for Flowers, Fruit & Vegetables RTU1 
Espoma Organic Copper Soap RTU1 
Monterey Liqui-Cop Copper Fungicidal Garden Spray Concentrate (8%) 
Monterey Liquid Copper Fungicide RTU1 (soap) 
Natural Guard Copper Soap Liquid Fungicide Concentrate (1.8%); & RTU1 
Southern Ag Liquid Copper Fungicide (8%) 
1 RTU products are pre-mixed fungicides in a spray bottle. 
2 For copper fungicide concentrates, the greater the metallic copper content, the better the control of bacterial & 
fungal diseases. 
Table 2. Tomato Cultivars with Resistance to Early Blight. 
Tomato Cultivar 
Other Disease 
Resistance* 
Plant Growth 
Habit** 
Days to 
Ripeness""",
    """Table 2. Tomato Cultivars with Resistance to Early Blight. 
Tomato Cultivar 
Other Disease 
Resistance* 
Plant Growth 
Habit** 
Days to 
Ripeness 
Mountain Supreme Hybrid VF D 69-70 
Mountain Fresh Hybrid VFF D 77 
Mountain Magic Hybrid VFF ISI 72 
Plum Regal Hybrid VFF D 72 
Plum Dandy Hybrid VF ISI 82""",
    """Cabernet Hybrid VFF I 60 
Manalucie FSt I 82 
Merlot Hybrid VFF I 59 
Tommy Toe (cherry) none I 70 
Mountain Merit Hybrid (moderate EB 
resist.) VFFFN TSWV LB D 75 
Jasper Hybrid (cherry) FF LB S D 60 
Iron Lady Hybrid LB S D 77 
Matt’s Wild Cherry (moderate EB 
resistance) LB (moderate) I 60 
Juliet Hybrid (mini-roma) (moderate EB 
resist) none I 60 
Defiant PhR Hybrid (moderate EB 
resistance) VFF LB D 70 
Legend (moderate EB resistance) LB D 68 
Old Brooks (moderate EB resistance) LB I 78 
Table 3. Tomato Cultivars with Resistance to Late Blight. 
Tomato Cultivar Other Disease Resistance* Plant Growth Habit** Days to Ripeness""",
    """Legend EB (moderate) D 68 
Mountain Magic Hybrid VFF EB ISI 72 
Plum Regal Hybrid VFF EB D 72 
Mountain Merit Hybrid VFFFN TSWV EB (Moderate) D 75 
Jasper Hybrid (cherry) FF EB S B 60 
Iron Lady Hybrid EB (moderate) S D 77 
Defiant PhR Hybrid 
VFF LB 
EB (moderate) D 70 
Matt’s Wild Cherry EB (moderate) I 60 
Table 4. Tomato Cultivars with Resistance to All 3 Races of Fusarium Wilt. 
Tomato Cultivar Disease Resistance* Plant Growth Habit** Days to Ripeness 
BHN 640 Hybrid VFFF TSWV D 75 
Charger Hybrid VFFFASt D 76 
Crista Hybrid VFFF TSWV D 73 
Floralina Hybrid VFFFA D 72 
Tasti-Lee Hybrid VFFF D 75""",
    """Solar Fire Hybrid VFFF D 72 
Top Gun Hybrid VFFFSt TSWV D 75 
Mountain Merit Hybrid VFFFN TSWV EB (moderate) D 75 
Table 5. Tomato Cultivars with Resistance to Tomato Spotted Wilt Virus (TSWV). 
Tomato Cultivar Disease Resistance* Plant Growth Habit** Days to Ripeness 
Bella Rosa Hybrid VFFASt TSWV D 75 
BHN 444 Hybrid VFF TSWV D 75 
BHN 640 Hybrid VFFF TSWV D 75 
Capaya Hybrid VFASt TSWV D 70 
Crista Hybrid VFFF TSWV D 73 
Fletcher Hybrid VN TSWV D 74 
Health Kick Hybrid VFFA TSWV D 74 
Plum Regal Hybrid VFF TSWV D 72 
Sophya Hybrid VFFSt TSWV I 75 
Talladaga Hybrid VFF TSWV D 60-67 
Top Gun Hybrid VFFFSt TSWV D 75""",
    """Mountain Merit hybrid VFFFN TSWV EB (partial) D 75 
Table 6. Tomato Cultivars with Resistance to Tomato Yellow Leaf Curl Virus (TYLCV). 
Tomato Cultivar Other Disease Resistance* Plant Growth Habit** Days to Ripeness 
Champion II Hybrid VFFNTA I 62-65 
Charger Hybrid VFFFASt D 76 
Margo Hybrid VFFT D 70 
Table 7. Tomato Cultivars with Resistance to Root-Knot Nematodes. 
Tomato Cultivar Disease Resistance* Plant Growth Habit** Days to Ripeness 
Beefmaster Hybrid VFNASt I 80 
Bella Rosa Hybrid VFFNA D 75 
Better Boy Hybrid VFNASt I 75 
Better Bush Hybrid VFN ISI 68 
Big Beef Hybrid VFFNTASt I 73 
Burpee’s Supersteak Hybrid VFN I 80 
Bush Early Girl II Hybrid VFFNT ISI 54 
Bush Goliath Hybrid VFN ISI 68""",
    """Celebrity Hybrid VFFNTASt ISI 70 
Champion II Hybrid VFNTA I 65-70 
Empire Hybrid VFFNASt D 72 
First Prize Hybrid VFFNT I 75 
Fletcher Hybrid VN TSWV D 74 
Goliath Hybrid VFFNT I 70 
Grandma’s Pick Hybrid VFN I 78-80 
Jetsetter Hybrid VFFNASt I 64 
Laroma III Hybrid VFFNA D 76 
MiRoma Hybrid VFFN D 70 
Park’s Whopper CR Improved Hybrid VFFNT I 65 
Royesta Hybrid FFNT I 70 
Super Fantastic Hybrid VFN I 70 
Super Marzano Hybrid VFNTA I 90 
Tiffany Hybrid VFNT I 70""",
    """Tomande Hybrid VFFNT I 68 
Tough Boy Hybrid VFN I 75 
Viva Italia Hybrid VFFNASt D 72 
Mountain Merit Hybrid VFFFN TSWV EB (moderate) D 75 
Table 8. Tomato Cultivars with Resistance to Blossom End Rot of Fruit. 
Tomato Cultivar Disease Resistance* Plant Growth Habit** Days to Ripeness 
Manalucie FSt EB I 82 
Mountain Spring Hybrid VFF D 72 
Mountain Fresh Hybrid VFF EB D 77 
New Yorker VA D 66 
Ravello Hybrid VFT I 60-65 
Wins All none I 80 
Table 9. Tomato Cultivars with Resistance to Cracking. 
Tomato Cultivar Disease Resistance* Plant Growth Habit** Days to Ripeness 
Abraham Lincoln Original none I 87 
Aunt Ginny’s Purple none I 75-85""",
    """Box Car Willie none I 80 
Campbell’s 33 Hybrid VFA D 69 
Celebrity Hybrid VFFNTASt ISI 70 
Charger Hybrid VFFFASt D 76 
Delicious none I 77 
Fantastic Hybrid VF I 65 
Gardener’s Delight none I 65 
German Head none I 80-90 
Heinz 1439 Hybrid VFA D 70 
Juliet Hybrid LB I 60 
Mountain Spring Hybrid VFF D 72 
New Yorker VA D 66 
Pilgrim Hybrid VFFASt D 68 
Pink Girl Hybrid VFT I 76 
Plum Regal Hybrid VFF TSWV D 80""",
    """Porter’s Pride none I 70 
Rutgers VFA D 75 
Super Sioux none ISI 70 
Supersonic Hybrid VF I 75-79 
Thessaloniki none I 75-80 
Tough Boy Hybrid VFN I 75 
Chef’s Choice Orange Hybrid T Anthracnose I 75 
Table 10. Tomato Cultivars with Resistance to Bacterial Speck. 
Tomato Cultivar Other Disease Resistance* Plant Growth Habit** Days to Ripeness 
Super Marzano Hybrid VFNT I 70-90 
Health Kick Hybrid VFFA TSWV D 74 
Viva Italia Hybrid VFFNA D 75 
Charger Hybrid VFFFASt D 76 
Mountain Pride Hybrid VFFASt D 77 
Marcellino Hybrid none I 75-80 
Ravello Hybrid VFT I 60-65""",
    """Tomatoberry Garden Hybrid none I 60-70""",
]
